-- ============================================================
-- Més Que Un Club - Schema completo
-- Aplicar en: Supabase SQL Editor o via supabase db push
-- ============================================================


-- ------------------------------------------------------------
-- EXTENSIONES
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_net";


-- ------------------------------------------------------------
-- TIPOS PERSONALIZADOS
-- ------------------------------------------------------------
CREATE TYPE match_status AS ENUM ('scheduled', 'live', 'finished');


-- ------------------------------------------------------------
-- SECUENCIAS
-- ------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS categories_id_seq;
CREATE SEQUENCE IF NOT EXISTS products_id_seq;
CREATE SEQUENCE IF NOT EXISTS purchases_id_seq;
CREATE SEQUENCE IF NOT EXISTS rifas_id_seq;
CREATE SEQUENCE IF NOT EXISTS rifa_boletos_id_seq;


-- ============================================================
-- TABLAS (en orden de dependencias)
-- ============================================================

-- ------------------------------------------------------------
-- logros (sin dependencias)
-- ------------------------------------------------------------
CREATE TABLE public.logros (
  id          bigint PRIMARY KEY,
  nombre      text,
  descripcion text,
  url_image   text
);

-- ------------------------------------------------------------
-- tipo_trofeo (sin dependencias)
-- ------------------------------------------------------------
CREATE TABLE public.tipo_trofeo (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_trofeo text NOT NULL,
  trofeo_url  text
);

-- ------------------------------------------------------------
-- categories (sin dependencias)
-- ------------------------------------------------------------
CREATE TABLE public.categories (
  id   integer NOT NULL DEFAULT nextval('categories_id_seq') PRIMARY KEY,
  name varchar NOT NULL
);

-- ------------------------------------------------------------
-- products (depende de categories)
-- ------------------------------------------------------------
CREATE TABLE public.products (
  id          integer NOT NULL DEFAULT nextval('products_id_seq') PRIMARY KEY,
  category_id integer NOT NULL REFERENCES public.categories(id),
  name        varchar NOT NULL,
  image_url   text,
  price       numeric NOT NULL,
  premium     boolean DEFAULT false,
  stock       smallint
);

-- ------------------------------------------------------------
-- profiles (depende de auth.users, logros, products)
-- ------------------------------------------------------------
CREATE TABLE public.profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email       text,
  nombre      text,
  url_avatar  text,
  membership  boolean DEFAULT false,
  monedas     numeric DEFAULT 0,
  puntos      bigint NOT NULL DEFAULT 0,
  nivel       smallint NOT NULL DEFAULT 0 CHECK (nivel >= 1 AND nivel <= 5),
  logro       bigint REFERENCES public.logros(id),
  logros      bigint NOT NULL DEFAULT 0,
  predicciones bigint DEFAULT 0,
  pais        text DEFAULT '',
  role        text NOT NULL DEFAULT 'user',
  is_banned   boolean DEFAULT false,
  banned_until timestamptz,
  insignia    integer REFERENCES public.products(id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- cartera (depende de profiles)
-- ------------------------------------------------------------
CREATE TABLE public.cartera (
  id              uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  id_usuario      uuid REFERENCES public.profiles(id),
  balance_real    numeric,
  balance_virtual numeric
);

-- ------------------------------------------------------------
-- transacciones (depende de cartera)
-- ------------------------------------------------------------
CREATE TABLE public.transacciones (
  id                uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  cartera_id        uuid REFERENCES public.cartera(id),
  monto             numeric,
  typo_transaccion  text,
  fecha_transaccion timestamptz
);

-- ------------------------------------------------------------
-- purchases (depende de profiles, products)
-- ------------------------------------------------------------
CREATE TABLE public.purchases (
  id         integer NOT NULL DEFAULT nextval('purchases_id_seq') PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.profiles(id),
  product_id integer NOT NULL REFERENCES public.products(id),
  amount     numeric NOT NULL
);

-- ------------------------------------------------------------
-- logros_obtenidos_usuarios (depende de profiles, logros)
-- ------------------------------------------------------------
CREATE TABLE public.logros_obtenidos_usuarios (
  id              bigint PRIMARY KEY,
  fecha_obtencion timestamptz,
  logro_id        bigint REFERENCES public.logros(id),
  usuario_id      uuid REFERENCES public.profiles(id)
);

-- ------------------------------------------------------------
-- fixtures (sin dependencias externas)
-- ------------------------------------------------------------
CREATE TABLE public.fixtures (
  fixture_id       text PRIMARY KEY,
  category         text NOT NULL CHECK (category = ANY (ARRAY['varonil','femenil'])),
  match_date       timestamptz NOT NULL,
  home_team        text NOT NULL,
  away_team        text NOT NULL,
  competition      text,
  venue            text,
  status           match_status DEFAULT 'scheduled',
  home_goals       integer DEFAULT 0,
  away_goals       integer DEFAULT 0,
  total_goals      integer DEFAULT 0,
  winner           text,
  first_scorer     text,
  halftime_result  integer CHECK (halftime_result = ANY (ARRAY[1, 0, -1])),
  updated_at       timestamptz DEFAULT now()
);

ALTER TABLE public.fixtures ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- matches_schedule
-- ------------------------------------------------------------
CREATE TABLE public.matches_schedule (
  fixture_id    bigint PRIMARY KEY,
  team_category varchar(50) NOT NULL,
  home_team     varchar(255) NOT NULL,
  away_team     varchar(255) NOT NULL,
  match_date    timestamptz NOT NULL,
  status_short  varchar(10) NOT NULL,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

ALTER TABLE public.matches_schedule ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- live_match_cache
-- ------------------------------------------------------------
CREATE TABLE public.live_match_cache (
  fixture_id     bigint PRIMARY KEY,
  fixture_date   timestamptz NOT NULL,
  status_elapsed integer,
  venue_name     text,
  venue_city     text,
  league_name    text,
  league_round   text,
  home_team_name text,
  away_team_name text,
  goals_home     integer,
  goals_away     integer,
  source_payload jsonb NOT NULL,
  fetched_at     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.live_match_cache ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- predicciones (depende de fixtures, auth.users)
-- ------------------------------------------------------------
CREATE TABLE public.predicciones (
  id                     uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  partido_id             text REFERENCES public.fixtures(fixture_id),
  user_id                uuid REFERENCES auth.users(id),
  ganador                text,
  goles_local            integer,
  goles_visitante        integer,
  goles_total            text,
  primer_goleador        text,
  resultado_medio_tiempo integer,
  UNIQUE (user_id, partido_id)
);

ALTER TABLE public.predicciones ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- usuarios_predicciones (depende de profiles, predicciones)
-- ------------------------------------------------------------
CREATE TABLE public.usuarios_predicciones (
  id               uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  usuario_id       uuid REFERENCES public.profiles(id),
  prediccion_id    uuid REFERENCES public.predicciones(id),
  fecha_prediccion timestamptz
);

-- ------------------------------------------------------------
-- watch_parties (depende de fixtures, auth.users)
-- ------------------------------------------------------------
CREATE TABLE public.watch_parties (
  id         uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  code       text NOT NULL UNIQUE,
  name       text NOT NULL,
  fixture_id text NOT NULL REFERENCES public.fixtures(fixture_id),
  home_team  text NOT NULL,
  away_team  text NOT NULL,
  match_date timestamptz NOT NULL,
  privacy    text NOT NULL DEFAULT 'publica' CHECK (privacy = ANY (ARRAY['publica','privada'])),
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.watch_parties ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- wordle_words
-- ------------------------------------------------------------
CREATE TABLE public.wordle_words (
  id      uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  word    text NOT NULL UNIQUE,
  used_on date UNIQUE
);

ALTER TABLE public.wordle_words ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- wordle_sessions (depende de auth.users)
-- ------------------------------------------------------------
CREATE TABLE public.wordle_sessions (
  id            uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id),
  date          date NOT NULL,
  guesses       text[] DEFAULT '{}',
  status        text DEFAULT 'in_progress',
  coins_awarded boolean DEFAULT false,
  UNIQUE (user_id, date)
);

ALTER TABLE public.wordle_sessions ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- trofeos (depende de tipo_trofeo)
-- ------------------------------------------------------------
CREATE TABLE public.trofeos (
  id          uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre      text NOT NULL,
  descripcion text,
  file_url    text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  tipo_trofeo bigint REFERENCES public.tipo_trofeo(id)
);

ALTER TABLE public.trofeos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- ubicacion_trofeo (depende de trofeos)
-- ------------------------------------------------------------
CREATE TABLE public.ubicacion_trofeo (
  id          uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  trofeo_id   uuid NOT NULL REFERENCES public.trofeos(id),
  latitud     text NOT NULL,
  longitud    text NOT NULL,
  nombre_lugar text
);

ALTER TABLE public.ubicacion_trofeo ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- usuarios_trofeos (depende de profiles, trofeos)
-- ------------------------------------------------------------
CREATE TABLE public.usuarios_trofeos (
  id              uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  usuario_id      uuid NOT NULL REFERENCES public.profiles(id),
  trofeo_id       uuid NOT NULL REFERENCES public.trofeos(id),
  fecha_obtencion timestamptz NOT NULL DEFAULT now(),
  UNIQUE (usuario_id, trofeo_id)
);

ALTER TABLE public.usuarios_trofeos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- barcelona_varonil_jugadores
-- ------------------------------------------------------------
CREATE TABLE public.barcelona_varonil_jugadores (
  id               uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre           text NOT NULL,
  numero           integer,
  posicion         text,
  goles            integer DEFAULT 0,
  asistencias      integer DEFAULT 0,
  atajadas         integer DEFAULT 0,
  goles_recibidos  integer DEFAULT 0,
  partidos_jugados integer DEFAULT 0,
  minutos_jugados  integer DEFAULT 0,
  imagen_url       text
);

ALTER TABLE public.barcelona_varonil_jugadores ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- barcelona_femenil_jugadores
-- ------------------------------------------------------------
CREATE TABLE public.barcelona_femenil_jugadores (
  id               uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre           text NOT NULL,
  numero           integer,
  posicion         text,
  goles            integer DEFAULT 0,
  asistencias      integer DEFAULT 0,
  atajadas         integer DEFAULT 0,
  goles_recibidos  integer DEFAULT 0,
  partidos_jugados integer DEFAULT 0,
  minutos_jugados  integer DEFAULT 0,
  imagen_url       text
);

ALTER TABLE public.barcelona_femenil_jugadores ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- estadisticas_mes_varonil (depende de barcelona_varonil_jugadores)
-- ------------------------------------------------------------
CREATE TABLE public.estadisticas_mes_varonil (
  id         uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  jugador_id uuid REFERENCES public.barcelona_varonil_jugadores(id),
  mes        text NOT NULL,
  año        integer NOT NULL,
  goles      integer DEFAULT 0
);

ALTER TABLE public.estadisticas_mes_varonil ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- estadisticas_mes_femenil (depende de barcelona_femenil_jugadores)
-- ------------------------------------------------------------
CREATE TABLE public.estadisticas_mes_femenil (
  id          uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  jugadora_id uuid REFERENCES public.barcelona_femenil_jugadores(id),
  mes         text NOT NULL,
  año         integer NOT NULL,
  goles       integer DEFAULT 0
);

ALTER TABLE public.estadisticas_mes_femenil ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- palmares_barcelona_unificado
-- ------------------------------------------------------------
CREATE TABLE public.palmares_barcelona_unificado (
  id              uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  equipo          text CHECK (equipo = ANY (ARRAY['Varonil','Femenil'])),
  nombre_oficial  text NOT NULL,
  nombre_agrupado text NOT NULL,
  ambito          text CHECK (ambito = ANY (ARRAY['Internacional','Nacional','Regional'])),
  cantidad        integer DEFAULT 0
);

ALTER TABLE public.palmares_barcelona_unificado ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- laliga_jugadores
-- ------------------------------------------------------------
CREATE TABLE public.laliga_jugadores (
  id        uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre    text NOT NULL,
  equipo    text,
  categoria text
);

ALTER TABLE public.laliga_jugadores ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- news_articles
-- ------------------------------------------------------------
CREATE TABLE public.news_articles (
  id         uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  guid       text NOT NULL UNIQUE,
  title      text,
  link       text,
  description text,
  image_url  text,
  pub_date   timestamptz,
  fetched_at timestamptz DEFAULT now()
);

-- ------------------------------------------------------------
-- selected_articles
-- ------------------------------------------------------------
CREATE TABLE public.selected_articles (
  id          uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title       text,
  link        text,
  description text,
  image_url   text,
  pub_date    timestamptz,
  selected_at timestamptz DEFAULT now()
);

ALTER TABLE public.selected_articles ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- friendships (depende de auth.users)
-- ------------------------------------------------------------
CREATE TABLE public.friendships (
  id         uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id),
  friend_id  uuid NOT NULL REFERENCES auth.users(id),
  status     text NOT NULL DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','accepted','request'])),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- videos
-- ------------------------------------------------------------
CREATE TABLE public.videos (
  id            uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  video_url     text NOT NULL,
  thumbnail_url text,
  caption       text,
  duration      integer,
  category      text,
  order_index   integer,
  is_active     boolean DEFAULT true,
  like_count    integer DEFAULT 0,
  created_at    timestamp DEFAULT now()
);

ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- user_video_actions (depende de auth.users, videos)
-- ------------------------------------------------------------
CREATE TABLE public.user_video_actions (
  user_id    uuid NOT NULL REFERENCES auth.users(id),
  video_id   uuid NOT NULL REFERENCES public.videos(id),
  liked      boolean DEFAULT false,
  watched    boolean,
  created_at timestamp DEFAULT now(),
  PRIMARY KEY (user_id, video_id)
);

ALTER TABLE public.user_video_actions ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- reportes (depende de profiles, watch_parties)
-- ------------------------------------------------------------
CREATE TABLE public.reportes (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  denunciante_id uuid NOT NULL REFERENCES public.profiles(id),
  denunciado_id  uuid NOT NULL REFERENCES public.profiles(id),
  watch_party_id uuid REFERENCES public.watch_parties(id),
  motivo         text NOT NULL,
  detalles       text,
  estado         text NOT NULL DEFAULT 'pendiente',
  creado_en      timestamptz DEFAULT timezone('utc', now()),
  resuelto_en    timestamptz,
  resuelto_por   uuid REFERENCES public.profiles(id)
);

ALTER TABLE public.reportes ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- error_reports (depende de profiles)
-- ------------------------------------------------------------
CREATE TABLE public.error_reports (
  id             uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id        uuid NOT NULL REFERENCES public.profiles(id),
  description    text NOT NULL,
  location       text NOT NULL,
  screenshot_url text,
  resolved       boolean NOT NULL DEFAULT false,
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.error_reports ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- rifas
-- ------------------------------------------------------------
CREATE TABLE public.rifas (
  id             integer NOT NULL DEFAULT nextval('rifas_id_seq') PRIMARY KEY,
  name           text NOT NULL,
  type           text NOT NULL CHECK (type = ANY (ARRAY['boleto','experiencia','viaje'])),
  total_boletos  integer NOT NULL DEFAULT 100,
  costo_monedas  numeric NOT NULL DEFAULT 2000,
  premium        boolean NOT NULL DEFAULT false,
  image_url      text,
  estado         text NOT NULL DEFAULT 'activa' CHECK (estado = ANY (ARRAY['activa','terminada'])),
  fecha_cierre   date,
  ganador_id     uuid REFERENCES public.profiles(id),
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE public.rifas ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- rifa_boletos (depende de rifas, profiles)
-- ------------------------------------------------------------
CREATE TABLE public.rifa_boletos (
  id         integer NOT NULL DEFAULT nextval('rifa_boletos_id_seq') PRIMARY KEY,
  rifa_id    integer NOT NULL REFERENCES public.rifas(id),
  user_id    uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.rifa_boletos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- rifa_ganadores (depende de rifas, profiles)
-- ------------------------------------------------------------
CREATE TABLE public.rifa_ganadores (
  id         uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  rifa_id    integer NOT NULL UNIQUE REFERENCES public.rifas(id),
  ganador_id uuid NOT NULL REFERENCES public.profiles(id),
  video_url  text,
  estado     text NOT NULL DEFAULT 'pendiente' CHECK (estado = ANY (ARRAY['pendiente','aceptado','denegado'])),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.rifa_ganadores ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- FUNCIONES
-- ============================================================

-- Calcula el nivel en base a puntos XP
CREATE OR REPLACE FUNCTION public.calcular_nivel(xp bigint)
RETURNS smallint LANGUAGE plpgsql AS $$
BEGIN
  IF xp >= 8000 THEN RETURN 5;
  ELSIF xp >= 6000 THEN RETURN 4;
  ELSIF xp >= 4000 THEN RETURN 3;
  ELSIF xp >= 2000 THEN RETURN 2;
  ELSE RETURN 1;
  END IF;
END;
$$;

-- Suma monedas al perfil de un usuario (evita race conditions)
CREATE OR REPLACE FUNCTION public.add_monedas(p_user_id uuid, p_amount integer)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.profiles
  SET monedas = monedas + p_amount
  WHERE id = p_user_id;
END;
$$;

-- Agrega una palabra al banco del Wordle
CREATE OR REPLACE FUNCTION public.add_word(new_word text, scheduled_date date DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO public.wordle_words (word, used_on)
  VALUES (LOWER(new_word), scheduled_date);
END;
$$;

-- Elimina una palabra del banco del Wordle
CREATE OR REPLACE FUNCTION public.delete_word(p_word text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM wordle_words WHERE word = p_word;
END;
$$;

-- Actualiza el logro activo de un usuario
CREATE OR REPLACE FUNCTION public.update_logro(user_id uuid, nuevo_logro bigint)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.profiles
  SET logro = nuevo_logro
  WHERE id = user_id;
END;
$$;

-- Devuelve los logros de un usuario indicando cuales ha desbloqueado
CREATE OR REPLACE FUNCTION public.get_user_logros(p_id uuid)
RETURNS TABLE(id bigint, nombre text, descripcion text, url_image text, desbloqueado boolean)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    l.id, l.nombre, l.descripcion, l.url_image,
    CASE WHEN lu.usuario_id IS NOT NULL THEN true ELSE false END AS desbloqueado
  FROM public.logros AS l
  LEFT JOIN public.logros_obtenidos_usuarios AS lu
    ON lu.logro_id = l.id AND lu.usuario_id = p_id
  ORDER BY l.id;
END;
$$;

-- Verifica si el usuario actual es admin
CREATE OR REPLACE FUNCTION public.is_admin_user()
RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- Genera un codigo unico de sala para Watch Party (formato XKP-7823)
CREATE OR REPLACE FUNCTION public.generate_unique_room_code()
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  new_code text;
  exists   boolean;
BEGIN
  LOOP
    new_code := upper(substring(md5(random()::text) FROM 1 FOR 3))
             || '-'
             || lpad(floor(random() * 9000 + 1000)::text, 4, '0');
    SELECT EXISTS (
      SELECT 1 FROM watch_parties WHERE code = new_code
    ) INTO exists;
    EXIT WHEN NOT exists;
  END LOOP;
  RETURN new_code;
END;
$$;

-- Valida un codigo de sala y devuelve la Watch Party
CREATE OR REPLACE FUNCTION public.validate_room_code(p_code text)
RETURNS TABLE(id uuid, code text, name text, fixture_id text, home_team text, away_team text, match_date timestamptz, privacy text, created_by uuid)
LANGUAGE sql AS $$
  SELECT id, code, name, fixture_id, home_team, away_team, match_date, privacy, created_by
  FROM watch_parties
  WHERE code = p_code
  LIMIT 1;
$$;

-- Devuelve los IDs de amigos aceptados de un usuario
CREATE OR REPLACE FUNCTION public.get_friend_ids(p_user_id uuid)
RETURNS TABLE(friend_id uuid) LANGUAGE sql AS $$
  SELECT friend_id FROM friendships WHERE user_id = p_user_id AND status = 'accepted'
  UNION
  SELECT user_id FROM friendships WHERE friend_id = p_user_id AND status = 'accepted';
$$;

-- Busca usuarios por nombre (para agregar amigos)
CREATE OR REPLACE FUNCTION public.buscar_amigos(texto_busqueda text)
RETURNS TABLE(id uuid, nombre_usuario text, url_avatar text, logro text)
LANGUAGE sql AS $$
  SELECT u.id, u.nombre, u.url_avatar, l.url_image
  FROM public.profiles AS u
  LEFT JOIN public.logros AS l ON u.logro = l.id
  WHERE u.nombre ILIKE texto_busqueda || '%'
  ORDER BY u.nombre
  LIMIT 10;
$$;

-- Devuelve amigos de un usuario con filtro de estado
CREATE OR REPLACE FUNCTION public.get_friends(p_user_id uuid, f_status text)
RETURNS TABLE(id uuid, nombre_usuario text, url_avatar text, logro text, status text)
LANGUAGE sql AS $$
  SELECT u.id, u.nombre, u.url_avatar, l.url_image, f.status
  FROM public.friendships AS f
  JOIN public.profiles AS u ON u.id = f.friend_id
  LEFT JOIN public.logros AS l ON u.logro = l.id
  WHERE f.user_id = p_user_id AND f.status = f_status;
$$;

-- Devuelve el estado de la relacion entre dos usuarios
CREATE OR REPLACE FUNCTION public.get_friend_status(sender_uuid uuid, receiver_uuid uuid)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  request_status text;
BEGIN
  SELECT f.status INTO request_status
  FROM public.friendships f
  WHERE (f.user_id = sender_uuid AND f.friend_id = receiver_uuid)
     OR (f.user_id = receiver_uuid AND f.friend_id = sender_uuid)
  LIMIT 1;
  RETURN COALESCE(request_status, 'none');
END;
$$;

-- Envia solicitud de amistad
CREATE OR REPLACE FUNCTION public.send_request(sender_uuid uuid, receiver_uuid uuid)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM public.friendships
  WHERE (user_id = sender_uuid AND friend_id = receiver_uuid)
     OR (user_id = receiver_uuid AND friend_id = sender_uuid);

  INSERT INTO public.friendships (user_id, friend_id, status)
  VALUES (sender_uuid, receiver_uuid, 'pending');

  INSERT INTO public.friendships (user_id, friend_id, status)
  VALUES (receiver_uuid, sender_uuid, 'request');
END;
$$;

-- Acepta solicitud de amistad
CREATE OR REPLACE FUNCTION public.accept_request(sender_uuid uuid, receiver_uuid uuid)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.friendships
  SET status = 'accepted'
  WHERE (user_id = sender_uuid AND friend_id = receiver_uuid)
     OR (user_id = receiver_uuid AND friend_id = sender_uuid);
END;
$$;

-- Elimina relacion de amistad
CREATE OR REPLACE FUNCTION public.delete_friendship(sender_uuid uuid, receiver_uuid uuid)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM public.friendships
  WHERE (user_id = sender_uuid AND friend_id = receiver_uuid)
     OR (user_id = receiver_uuid AND friend_id = sender_uuid);
END;
$$;

-- Lista trofeos con coordenadas geograficas
CREATE OR REPLACE FUNCTION public.obtener_lista_trofeos()
RETURNS TABLE(id uuid, nombre text, descripcion text, coordenadas float8[])
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT t.id, t.nombre::TEXT, t.descripcion::TEXT,
         ARRAY[u.latitud, u.longitud]::FLOAT8[] AS coordenadas
  FROM trofeos t
  INNER JOIN ubicacion_trofeo u ON t.id = u.trofeo_id;
END;
$$;

-- Trigger function: crea perfil automaticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nombre, url_avatar)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', 'Nuevo Socio'),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', NEW.raw_user_meta_data->>'picture', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'Error en handle_new_user para el usuario %: %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

-- Trigger function: recalcula nivel al actualizar puntos
CREATE OR REPLACE FUNCTION public.actualizar_nivel()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.puntos > 8000 THEN NEW.puntos := 8000; END IF;
  IF NEW.puntos < 0 THEN NEW.puntos := 0; END IF;
  NEW.nivel := calcular_nivel(NEW.puntos);
  RETURN NEW;
END;
$$;


-- ============================================================
-- TRIGGERS
-- ============================================================

-- Crea perfil automaticamente cuando se registra un usuario
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Recalcula nivel cuando cambian los puntos del perfil
CREATE TRIGGER trigger_actualizar_nivel
  BEFORE INSERT OR UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.actualizar_nivel();


-- ============================================================
-- POLITICAS RLS
-- ============================================================

-- profiles
CREATE POLICY "Allow read for all"       ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_select_own"      ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own"      ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own"      ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_admin"    ON public.profiles FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')) WITH CHECK (true);
CREATE POLICY "Only admins can view all" ON public.profiles FOR SELECT USING (is_admin_user() OR (id = auth.uid()));

-- fixtures
CREATE POLICY "Cualquiera puede ver los partidos" ON public.fixtures FOR SELECT USING (true);

-- matches_schedule
CREATE POLICY "Lectura publica de partidos" ON public.matches_schedule FOR SELECT USING (true);

-- live_match_cache
CREATE POLICY "read live_match_cache" ON public.live_match_cache FOR SELECT TO anon, authenticated USING (true);

-- predicciones
CREATE POLICY "Todos los usuarios logueados pueden ver predicciones" ON public.predicciones FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuario inserta sus predicciones"   ON public.predicciones FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Usuario actualiza sus predicciones" ON public.predicciones FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Usuario borra sus predicciones"     ON public.predicciones FOR DELETE USING (auth.uid() = user_id);

-- watch_parties
CREATE POLICY "Public watch parties are viewable by everyone"        ON public.watch_parties FOR SELECT USING (privacy = 'publica');
CREATE POLICY "Owner can view own watch parties"                     ON public.watch_parties FOR SELECT USING (auth.uid() = created_by);
CREATE POLICY "Friends can view each other private watch parties"    ON public.watch_parties FOR SELECT USING (privacy = 'privada' AND created_by IN (SELECT get_friend_ids(auth.uid())));
CREATE POLICY "Authenticated users can create watch parties"        ON public.watch_parties FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Owner can delete own watch parties"                   ON public.watch_parties FOR DELETE USING (auth.uid() = created_by);

-- wordle_words
CREATE POLICY "read_wordle" ON public.wordle_words FOR SELECT USING (true);

-- wordle_sessions
CREATE POLICY "own session select" ON public.wordle_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "own session insert" ON public.wordle_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "own session update" ON public.wordle_sessions FOR UPDATE USING (auth.uid() = user_id);

-- barcelona_varonil_jugadores
CREATE POLICY "read_varonil_jugadores" ON public.barcelona_varonil_jugadores FOR SELECT TO anon, authenticated USING (true);

-- barcelona_femenil_jugadores
CREATE POLICY "read_femenil_jugadores" ON public.barcelona_femenil_jugadores FOR SELECT TO anon, authenticated USING (true);

-- estadisticas_mes_varonil
CREATE POLICY "read_estadisticas_mes_varonil" ON public.estadisticas_mes_varonil FOR SELECT TO anon, authenticated USING (true);

-- estadisticas_mes_femenil
CREATE POLICY "read_estadisticas_mes_femenil" ON public.estadisticas_mes_femenil FOR SELECT TO anon, authenticated USING (true);

-- palmares_barcelona_unificado
CREATE POLICY "read_palmares_unificado" ON public.palmares_barcelona_unificado FOR SELECT TO anon, authenticated USING (true);

-- laliga_jugadores
CREATE POLICY "Enable read access for all users" ON public.laliga_jugadores FOR SELECT TO authenticated USING (true);

-- selected_articles
CREATE POLICY "Leer selected articles"    ON public.selected_articles FOR SELECT USING (true);
CREATE POLICY "Insertar selected articles" ON public.selected_articles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Borrar selected articles"  ON public.selected_articles FOR DELETE TO authenticated USING (true);

-- friendships
CREATE POLICY "Allow read for all" ON public.friendships FOR SELECT USING (true);

-- videos
CREATE POLICY "Anyone can view videos"  ON public.videos FOR SELECT USING (true);
CREATE POLICY "Admins can insert videos" ON public.videos FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Admins can update videos" ON public.videos FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Admins can delete videos" ON public.videos FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- user_video_actions
CREATE POLICY "Users manage their actions" ON public.user_video_actions FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- trofeos
CREATE POLICY "trofeos_select" ON public.trofeos FOR SELECT TO authenticated USING (true);
CREATE POLICY "trofeos_insert" ON public.trofeos FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "trofeos_update" ON public.trofeos FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "trofeos_delete" ON public.trofeos FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- ubicacion_trofeo
CREATE POLICY "ubicacion_select" ON public.ubicacion_trofeo FOR SELECT TO authenticated USING (true);
CREATE POLICY "ubicacion_insert" ON public.ubicacion_trofeo FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "ubicacion_update" ON public.ubicacion_trofeo FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "ubicacion_delete" ON public.ubicacion_trofeo FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- usuarios_trofeos
CREATE POLICY "ut_select" ON public.usuarios_trofeos FOR SELECT TO authenticated USING (usuario_id = auth.uid());
CREATE POLICY "ut_insert" ON public.usuarios_trofeos FOR INSERT TO authenticated WITH CHECK (usuario_id = auth.uid());

-- reportes
CREATE POLICY "Cualquier usuario autenticado puede crear reportes"          ON public.reportes FOR INSERT TO authenticated WITH CHECK (auth.uid() = denunciante_id);
CREATE POLICY "Solo los administradores tienen control total de los reportes" ON public.reportes FOR ALL TO authenticated USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

-- error_reports
CREATE POLICY "Enable read access for auth users" ON public.error_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert error reports"    ON public.error_reports FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for authenticated users" ON public.error_reports FOR UPDATE USING (auth.role() = 'authenticated');

-- rifas
CREATE POLICY "public_read_active_rifas" ON public.rifas FOR SELECT USING (estado = 'activa');
CREATE POLICY "admins_all_rifas"         ON public.rifas FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')) WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- rifa_boletos
CREATE POLICY "public_read_boletos_count" ON public.rifa_boletos FOR SELECT USING (true);
CREATE POLICY "users_read_own_boletos"    ON public.rifa_boletos FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "users_insert_own_boleto"   ON public.rifa_boletos FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "admins_all_boletos"        ON public.rifa_boletos FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')) WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- rifa_ganadores
CREATE POLICY "ganador_select_own" ON public.rifa_ganadores FOR SELECT TO authenticated USING (ganador_id = auth.uid());
CREATE POLICY "ganador_insert_own" ON public.rifa_ganadores FOR INSERT TO authenticated WITH CHECK (ganador_id = auth.uid());
CREATE POLICY "admins_all_ganadores" ON public.rifa_ganadores FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')) WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
